# Generated by Django 2.0.6 on 2018-07-04 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortname', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('parent_task_num', models.IntegerField(blank=True, null=True)),
                ('expected_start_date', models.DateField()),
                ('expected_end_date', models.DateField(blank=True, null=True)),
                ('actual_start_date', models.DateField(blank=True, null=True)),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('effective_start_date', models.DateTimeField(auto_now_add=True)),
                ('effective_end_date', models.DateTimeField(auto_now=True, null=True)),
                ('version_number', models.IntegerField()),
                ('is_current', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='updated_tasks', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='proyects.Project')),
                ('user_responsible', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('task_num', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('expected_time', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actual_time', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('unit', models.CharField(choices=[('Hours', 'Hours'), ('Days', 'Days'), ('Months', 'Months')], max_length=20)),
                ('is_complete', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('effective_start_date', models.DateTimeField(auto_now_add=True)),
                ('effective_end_date', models.DateTimeField(null=True)),
                ('version_number', models.IntegerField()),
                ('is_current', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='created_taskitems', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='updated_taskitems', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='proyects.Project')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_num', models.IntegerField()),
                ('text', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_complete_attr', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='proyects.Project')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
